deployment:
  metadata.namespace: __namespace
  spec.replicas: replicas
  spec.template.spec.containers.#.name: container_name
  spec.template.spec.containers.#.image: image
  spec.template.spec.containers.#.imagePullPolicy: imagePullPolicy


configmap:
  metadata.namespace: __namespace
  data: data

secret:
  metadata.namespace: __namespace
  data: data

ingress:
  metadata.namespace: __namespace
  spec.rules.#.host: host
  spec.tls: tls

persistentvolumeclaim:
  metadata.namespace: __namespace
  spec: spec

service:
  metadata.namespace: __namespace

serviceaccount:
  metadata.namespace: __namespace

role:
  metadata.namespace: __namespace

rolebinding:
  metadata.namespace: __namespace

clusterrole:
  metadata.namespace: __namespace

clusterrolebinding:
  metadata.namespace: __namespace

